# Generated by Django 3.2.6 on 2021-08-12 20:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('repo_link', models.CharField(max_length=255)),
                ('card_img', models.CharField(max_length=255)),
                ('showcase', models.BooleanField(default=False)),
                ('live_demo', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.OneToOneField(default=uuid.uuid1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('tag', models.ManyToManyField(to='blog.Tag')),
            ],
        ),
    ]
