# Generated by Django 5.2 on 2026-01-31

from django.db import migrations, models
import django.db.models.deletion
import ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=36)),
                ("last_name", models.CharField(max_length=36)),
                ("email", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("body", ckeditor.fields.RichTextField(blank=True)),
                ("date_published", models.DateField()),
                ("repo_link", models.CharField(blank=True, max_length=255, null=True)),
                ("banner_img", models.ImageField(blank=True, null=True, upload_to="blog/banner_img")),
                ("card_img", models.ImageField(blank=True, null=True, upload_to="blog/card_img")),
                ("lang", models.CharField(choices=[("ES", "Español"), ("EN", "English")], default="EN", max_length=2)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="blog.author")),
                ("tag", models.ManyToManyField(to="blog.tag")),
            ],
            options={
                "ordering": ["-date_published"],
            },
        ),
    ]
