# Generated by Django 5.2 on 2026-01-31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20210813_1544"),
    ]

    operations = []
